apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "goweb.com/v1alpha1",
          "kind": "GoWebApp",
          "metadata": {
            "name": "gowebapp-sample"
          },
          "spec": {
            "frontend": {
              "image": "docker.io/ishasangrolkar/demo-app:latest",
              "imagePullSecrets": [],
              "replicaCount": 1,
              "service": {
                "port": 3000,
                "targetPort": 3000,
                "type": "NodePort"
              }
            }
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.2.0
    operators.operatorframework.io/project_layout: ansible.sdk.operatorframework.io/v1
  name: goweb-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: GoWebApp
      name: gowebapps.goweb.com
      version: v1alpha1
  description: This operator will deploy a simple go based application
  displayName: Goweb operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          - pods
          - pods/exec
          - pods/log
          - namespaces
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - goweb.com
          resources:
          - gowebapps
          - gowebapps/status
          - gowebapps/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - persistentvolumeclaims
          - persistentvolumes
          - nodes
          - events
          - secrets
          - secrets/finalizers
          - pods
          - pods/finalizers
          - serviceaccounts
          - services
          - configmaps
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - networking.k8s.io
          resources:
          - ingresses
          verbs:
          - '*'
        - apiGroups:
          - security.openshift.io
          resourceNames:
          - anyuid
          resources:
          - securitycontextconstraints
          verbs:
          - use
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - secrets
          - secrets/finalizers
          - pods
          - pods/finalizers
          - pods/exec
          - pods/log
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - persistentvolumes
          - persistentvolumeclaims/finalizers
          - persistentvolumes/finalizers
          - nodes
          - events
          - configmaps
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: goweb-operator
      deployments:
      - name: goweb-operator-goweb-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: goweb-operator
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: goweb-operator
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:3000/
                - --logtostderr=true
                - --v=10
                image: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.6.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --metrics-addr=127.0.0.1:3000
                - --enable-leader-election
                - --leader-election-id=goweb-operator
                env:
                - name: ANSIBLE_GATHERING
                  value: explicit
                - name: OPERATOR_NAME
                  value: goweb-operator
                - name: RELATED_IMAGE_FRONTEND
                  value: docker.io/ishasangrolkar/demo-app:latest
                image: quay.io/isha98/goweb-operator1
                imagePullPolicy: Always
                name: manager
                resources: {}
              serviceAccountName: goweb-operator
              terminationGracePeriodSeconds: 10
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - goweb-operator
  - frontend
  links:
  - name: Goweb Operator
    url: https://goweb-operator.domain
  maturity: alpha
  provider:
    name: Isha
  version: 0.0.1
